name: CI-test

on:
  pull_request:
    branches:
    - main

jobs:
  build_stats:
    name: CI-test
    runs-on: ubuntu-latest

    steps:
    - name: Dependencies
      run: sudo apt update && sudo apt install -y build-essential gcc-arm-none-eabi binutils-arm-none-eabi && python -m pip install requests argparse

    - uses: actions/checkout@v3

    - name: Install agbcc
      run: tools/install_agbcc.sh

    - name: Generate dummy base ROM
      run: head -c 8M /dev/urandom > fe6-base.gba

    - name: Build target ROM
      run: make -j fe6.gba
